"""Generate the OLC format reference for AI agents, and keep every agent skill current.

Agents (Claude, Codex, Cursor, Copilot, … and LakeLogic's Zeus) write contracts from what
they are told. Told nothing, they fall back on other tools' habits — ``rules:`` /
``type:`` / ``assertion:`` instead of ``quality.dataset_rules`` with ``sql`` — and the
result looks plausible and fails validation. So the format they are given is GENERATED
from the committed JSON Schema (itself generated from ``OLCContractV1``), never
hand-written, and it cannot drift: ``tests/test_reference_drift.py`` fails when it does.

Outputs:
  * ``skills/olc-reference.md`` — the full reference (bundled into ``olc/_bundled/skills``
    by setup.py, so an installed ``olc`` carries the version that matches its schema).
  * A marked block in every standing-context skill file (AGENTS.md, SKILL.md, Cursor /
    Copilot / Cline / … rules). Files that have no block yet get one appended — the
    release "extends the skills when needed"; files that already match are not touched.

    python scripts/generate_reference.py          # write
    python scripts/generate_reference.py --check  # exit 1 if anything is stale
"""

from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCHEMA_PATH = ROOT / "schema" / "open-lakehouse-contract.schema.json"
REFERENCE_PATH = ROOT / "skills" / "olc-reference.md"

START = "<!-- OLC-REFERENCE:START — generated by scripts/generate_reference.py; do not edit by hand -->"
END = "<!-- OLC-REFERENCE:END -->"

#: Skill files an agent reads as standing context. Command/prompt files (one verb each)
#: are not listed: they run inside an agent that already has one of these loaded.
CONTEXT_FILES = [
    "skills/agents/AGENTS.md",
    "skills/claude/skills/olc/SKILL.md",
    "skills/copilot/copilot-instructions.md",
    "skills/cursor/rules/open-lakehouse-contract.mdc",
    "skills/cline/open-lakehouse-contract.md",
    "skills/windsurf/rules/open-lakehouse-contract.md",
    "skills/amazonq/rules/open-lakehouse-contract.md",
    "skills/roo/rules/open-lakehouse-contract.md",
    "skills/kilocode/rules/open-lakehouse-contract.md",
    "skills/gemini/root/GEMINI.md",
]

#: Shapes agents most often get wrong, shown as valid examples.
EXAMPLES = """```yaml
quality:
  fail_pipeline_on_dataset_error: true
  row_rules:                       # checked per row; failing rows are quarantined
    - not_null: [trip_id, pickup_at]
    - accepted_values: {field: status, values: [completed, cancelled]}
    - name: fare_non_negative
      category: validity           # completeness | uniqueness | validity | consistency | accuracy
      description: Fares are never negative
      sql: "fare_amount >= 0"
      severity: error
  dataset_rules:                   # checked once per run, over the whole dataset
    - unique: trip_id
    - row_count_between: {min: 1}
    - name: dropoff_after_pickup
      category: consistency
      sql: "SELECT SUM(CASE WHEN dropoff_at < pickup_at THEN 1 ELSE 0 END) = 0 FROM source"
transformations:
  - phase: pre
    sql: "SELECT * FROM source WHERE trip_id IS NOT NULL"
  - phase: post
    derive: {field: duration_minutes, sql: "date_diff('minute', pickup_at, dropoff_at)"}
```

There is no `rules:`, `type:`, `assertion:`, `checks:` or `tests:` key anywhere in a
contract. Unknown keys are rejected."""


def _type(node: dict, defs: dict) -> str:
    if "$ref" in node:
        return node["$ref"].rsplit("/", 1)[-1]
    if "enum" in node:
        return " | ".join(json.dumps(v) for v in node["enum"])
    if "const" in node:
        return json.dumps(node["const"])
    for key in ("anyOf", "oneOf"):
        if key in node:
            parts = [p for p in node[key] if p.get("type") != "null"]
            optional = len(parts) != len(node[key])
            inner = " | ".join(_type(p, defs) for p in parts) or "null"
            return inner + (" (nullable)" if optional else "")
    t = node.get("type")
    if t == "array":
        return f"list[{_type(node.get('items', {}), defs)}]"
    if t == "object":
        extra = node.get("additionalProperties")
        if isinstance(extra, dict):
            return f"map[string → {_type(extra, defs)}]"
        return "object (free-form)" if extra is not False else "object"
    return t or "any"


def _refs(node: object) -> list[str]:
    out: list[str] = []
    if isinstance(node, dict):
        if "$ref" in node:
            out.append(node["$ref"].rsplit("/", 1)[-1])
        for v in node.values():
            out.extend(_refs(v))
    elif isinstance(node, list):
        for v in node:
            out.extend(_refs(v))
    return out


def _first_sentence(text: str | None) -> str:
    if not text:
        return ""
    line = " ".join(text.strip().split())
    cut = line.find(". ")
    return line if cut == -1 else line[: cut + 1]


def _table(obj: dict, defs: dict) -> list[str]:
    props = obj.get("properties", {})
    if not props:
        return ["_(free-form object)_", ""]
    required = set(obj.get("required", []))
    rows = ["| key | type | notes |", "|---|---|---|"]
    for name, node in props.items():
        notes = []
        if name in required:
            notes.append("**required**")
        if "default" in node and node["default"] not in (None, [], {}):
            notes.append(f"default `{json.dumps(node['default'])}`")
        # The whole description: meaning, default and example are what an agent needs, and the
        # first sentence alone dropped them (it also cut at "e.g.").
        desc = " ".join((node.get("description") or "").split())
        if desc:
            notes.append(desc.replace("|", "\\|"))
        rows.append(
            f"| `{name}` | {_type(node, defs).replace('|', chr(92) + '|')} | {' · '.join(notes)} |"
        )
    closed = obj.get("additionalProperties") is False
    return rows + [
        "",
        "Unknown keys rejected." if closed else "Other keys allowed.",
        "",
    ]


def build_reference(schema: dict) -> str:
    defs = schema.get("$defs", {})
    digest = hashlib.sha256(json.dumps(schema, sort_keys=True).encode()).hexdigest()[
        :12
    ]
    out = [
        "# Open Lakehouse Contract — format reference",
        "",
        f"Generated from `schema/open-lakehouse-contract.schema.json` (sha `{digest}`). Do not",
        "edit by hand: run `python scripts/generate_reference.py`. When writing or changing a",
        "contract, use ONLY the keys below, then validate with `olc validate <path>`.",
        "",
        "## Common shapes",
        "",
        EXAMPLES,
        "",
        "## Top level",
        "",
        *_table(schema, defs),
    ]
    # Every definition reachable from the root, in first-use order.
    order: list[str] = []
    queue = _refs(schema.get("properties", {}))
    while queue:
        name = queue.pop(0)
        if name in order or name not in defs:
            continue
        order.append(name)
        queue.extend(_refs(defs[name]))
    for name in order:
        d = defs[name]
        out += [f"## {name}", ""]
        desc = _first_sentence(d.get("description"))
        if desc:
            out += [desc, ""]
        out += _table(d, defs)
    return "\n".join(out).rstrip() + "\n"


def _with_block(text: str, reference: str) -> str:
    block = f"{START}\n{reference.rstrip()}\n{END}"
    if START in text and END in text:
        head, rest = text.split(START, 1)
        _, tail = rest.split(END, 1)
        return head + block + tail
    return text.rstrip() + "\n\n" + block + "\n"


def planned_writes(schema: dict) -> dict[Path, str]:
    reference = build_reference(schema)
    writes = {REFERENCE_PATH: reference}
    for rel in CONTEXT_FILES:
        path = ROOT / rel
        if path.exists():
            writes[path] = _with_block(path.read_text(encoding="utf-8"), reference)
    return writes


def stale(schema: dict) -> list[Path]:
    return [
        p
        for p, text in planned_writes(schema).items()
        if not p.exists() or p.read_text(encoding="utf-8") != text
    ]


def main(argv: list[str]) -> int:
    schema = json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))
    if "--check" in argv:
        bad = stale(schema)
        for p in bad:
            print(f"stale: {p.relative_to(ROOT)}")
        return 1 if bad else 0
    changed = 0
    for path, text in planned_writes(schema).items():
        if not path.exists() or path.read_text(encoding="utf-8") != text:
            path.write_text(text, encoding="utf-8", newline="\n")
            changed += 1
            print(f"updated {path.relative_to(ROOT)}")
    print(f"OLC reference: {changed} file(s) updated")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
